# Generated by Django 5.2.1 on 2025-05-26 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='queued_users',
            field=models.ManyToManyField(blank=True, related_name='queued_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
